### ISSUE TITLE
Implement new /search/ interface with both projects and bugs (see mockup that lives somewhere)

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1000] opened 2014-08-08 02:54 UTC
<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Right now, and even on the redesign, the /search/ page that lets one browse for
volunteer opportunities only browses for individual bugs.

Instead, it should provide an interface for letting the user choose between two
modes: searching for a project (i.e., a community) vs. searching for a specific
task.

This came up as something for the 0.12.02 redesign, but seems farther off down
the pipeline.
   
</dl></dd><hr/>

Status: <b>unread</b>
Nosy List: <b>  paulproteus </b>
Priority: <b>wish</b>
Imported from roundup ID: <b>685</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue685'>view archived page</a>)
Last modified: <b>2012-02-15.22:26:04</b>

**Comment by ehashman** [comment] 2015-04-16 20:11
Closing as a duplicate of #1029.

**Closed by ehashman** 2015-04-16 20:11 UTC
Labels: milestone:later, pri:wish, search, stat:unread
