### ISSUE TITLE
Error 500 at subversion (mission 3)

### ISSUE THREAD

**Issue by angelusbr** [openhatch/oh-mainline#1547] opened 2015-03-04 00:02 UTC
![captura de tela de 2015-03-03 20 59 41](https://cloud.githubusercontent.com/assets/11271294/6475400/8408f0e2-c1e8-11e4-93d0-1d267ab4c376.png)

I have submited the following text:

Index: README
===================================================================
--- README	(revisão 3)
+++ README	(cópia de trabalho)
@@ -1,5 +1,5 @@
 The secret word needed to infiltrate the compound is in word.txt. You
-also will need to be wearing a red hat.  Good luck on your mision!
+also will need to be wearing a red hat.  Good luck on your mission!
 
   -- Mr. Bad

**Comment by angelusbr** [comment] 2015-03-04 15:11
the text is, with "=":

Index: README
===================================================================
--- README	(revisão 3)
+++ README	(cópia de trabalho)
@@ -1,5 +1,5 @@
 The secret word needed to infiltrate the compound is in word.txt. You
-also will need to be wearing a red hat.  Good luck on your mision!
+also will need to be wearing a red hat.  Good luck on your mission!
 
   -- Mr. Bad

**Comment by moijes12** [comment] 2015-03-13 20:28
![screenshot](https://cloud.githubusercontent.com/assets/4566851/6646683/c60591be-c984-11e4-91bf-2d4362f69733.jpg)

Works just fine for me

**Comment by willingc** [comment] 2015-03-30 23:55
@angelusbr Thanks for submitting this issue. As a developer, I really appreciate the extra time that you spent adding screenshots since they are very helpful.

This is a known issue that we are working on resolving. Thank you for providing additional information. :penguin: :cake:

Close issue as duplicate of #1399

**Closed by willingc** 2015-03-30 23:55 UTC
Labels: duplicate, pri:bug
