### ISSUE TITLE
Footer overshadowing mission body in Chrome (43)

### ISSUE THREAD

**Issue by waseem18** [openhatch/oh-mainline#1656] opened 2015-05-23 11:56 UTC
While browsing Training missions (http://openhatch.org/missions/) I found that the footer is overshadowing some part of the body. All the subpages of Training missions are behaving the same way in Chrome(43). This issue is only with Chrome(43). It works fine with Mozilla and IE and also with previous version of Chrome. 

Attached images:

![m2](https://cloud.githubusercontent.com/assets/5843007/7783913/a0cf9e52-0170-11e5-932e-e4166e834f31.PNG)

![m1](https://cloud.githubusercontent.com/assets/5843007/7783914/a0d32590-0170-11e5-9b53-6526569198ad.PNG)

**Comment by willingc** [comment] 2015-05-23 14:53
@waseem18 Thanks for filing this issue report. Would you mind clearing the cache on your version of Chrome and seeing if that resolves the issue?

We've been chatting about this in issue 1641 https://github.com/openhatch/oh-mainline/issues/1641.

**Comment by waseem18** [comment] 2015-05-23 16:40
@willingc Yeah! After I cleared the cache, webpage rendered correctly.

**Comment by willingc** [comment] 2015-05-23 16:46
@waseem18 Great. I'm glad that worked for you.

Closing this issue as a duplicate of #1641.

**Closed by willingc** 2015-05-23 16:46 UTC
Labels: duplicate
