### ISSUE TITLE
JSON error when editing project link in profile

### ISSUE THREAD

**Issue by willingc** [openhatch/oh-mainline#1510] opened 2014-12-31 13:56 UTC
As reported by Anurag via email:

Hello everyone,

Yesterday I was trying to update my portfolio on Openhatch, but couldn't add a "link" in the project section. After clicking the "save" the page freezes.
I tried refreshing several times but no improvement.

I am attaching a snapshot with this mail, which contains an error message from the console as well.

Thanks
![screenshot from 2014-12-31 18-04-28](https://cloud.githubusercontent.com/assets/2680980/5588003/909eb0de-90b1-11e4-8c06-8d18926a659b.png)

**Comment by anurag619** [comment] 2015-01-06 14:20
So, basically I just have to replace simplejson with json?

**Comment by willingc** [comment] 2015-01-06 15:54
@anurag619 Yes, you would import json instead of simplejson. I would also look at all of the json and simplejson mentions in the file and see if any of them need to be edited. Thanks.

**Comment by anurag619** [comment] 2015-01-07 12:20
Strange, I am able to add urls now, did anyone added some code there ?

Also I would like to add, what if I want to remove/edit the added urls ?

**Comment by jlachewitz** [comment] 2015-04-13 16:05
Unable to reproduce this bug on Firefox Version 36.0.4 and Chrome Version 41.0.2272.118 (64-bit).  Seems like this may have been fixed by a prior change.

**Closed** 2015-04-13 16:31 UTC
Labels: bitesize, frontend, pri:bug, stat:in-progress
