### ISSUE TITLE
Footer floating over text in live environment

### ISSUE THREAD

**Issue by NPrescott** [openhatch/oh-mainline#1599] opened 2015-04-15 07:27 UTC
A recent change has broken the footer so that it now floats over the text of the page. A quick looks indicates it's on every page. On Firefox 37.0.1 and Chrome 41.0.2272.118 - OSX 10.9.5 I see the following:

![footer-bug](https://cloud.githubusercontent.com/assets/4661088/7153790/6bfc47e6-e31d-11e4-9fc3-9fa5232f56e2.png)

Curiously, I can't entirely recreate this bug locally. Although I can see an issue with the footer floating off-center. As seen here:

![local-footer-bug](https://cloud.githubusercontent.com/assets/4661088/7153854/18f2c876-e31e-11e4-983c-ecfb947d032e.png)

Which I've identified as stemming from commit 1fa255d520f1a48316f2065cffbd8c265c2e0143. No idea yet why I can't entirely recreate it (I've cleared my browser cache etc.).

**Comment by mestaritonttu** [comment] 2015-04-15 07:41
Unable to reproduce with Firefox 37.0.1 on Win 7. Footer is centered and where it should be when I visit http://openhatch.org/missions/git

**Comment by NPrescott** [comment] 2015-04-15 09:07
As far as I can tell, the issue is caused by:

    #footer-wrapper {
        ....
        position:  absolute;
    }

Along with the removal of a closing `</div>` tag. I don't know CSS well enough to recommend a complete fix, the following patch results in some oddities (but is arguably more usable in spite of them):

```diff
diff --git a/mysite/base/templates/base/base.html b/mysite/base/templates/base/base.html
index 299278a..4ea4ca0 100644
--- a/mysite/base/templates/base/base.html
+++ b/mysite/base/templates/base/base.html
@@ -155,6 +155,7 @@
                 </div><!-- /#content -->
                <div class="clearfix"></div>
         </div><!-- /#container -->
+        </div>

         <div id='footer-wrapper'>
           <div id='footer'>
diff --git a/mysite/static/less/base/base.less b/mysite/static/less/base/base.less
index 5b0ee56..f7ff2d6 100644
--- a/mysite/static/less/base/base.less
+++ b/mysite/static/less/base/base.less
@@ -95,7 +95,7 @@ body {
     width: 100%;
     .centered;
     padding: 0;
-    margin-bottom: @footer-height;
+    margin-bottom: 0px
 }

 code {
@@ -139,7 +139,7 @@ abbr.foss { border: 0; font-variant: small-caps;}

 h1 a, h1 a:hover { text-decoration: none; }

-#container { width: @total-width; padding-bottom: 30px; .centered;}
+#container { width: @total-width; .centered;}

 .module {
     width: 100%;
@@ -239,7 +239,6 @@ ul#links { margin-left: 20px; }
     width: 100%;
     clear: both;
     padding-top: 40px;
-    position: absolute;
     bottom: 0;
 }
```

The People page still has issues even with the above changes (I haven't bothered to track where the `padding-bottom` is introduced as I don't think this is a complete fix):

![screen shot 2015-04-15 at 4 46 52 am](https://cloud.githubusercontent.com/assets/4661088/7155194/a37350a4-e32a-11e4-9c6a-c4df6a3ac1fe.png)

I'll probably hold off on a PR until a root cause for the differences between dev and production is identified (unless I hear otherwise). Not sure of any gains to be made chasing this any further at present.

**Comment by ehashman** [comment] 2015-04-15 14:41
I also noted this [on #1437](https://github.com/openhatch/oh-mainline/issues/1437#issuecomment-93401230); I'm worried that the fix in #1586 caused this. I'm going to try a local revert and see if that fixes things.

**Comment by paulproteus** [comment] 2015-04-15 16:09
Hi @NPrescott and @ableman -- please feel very free to work on this. It's a pretty important thingamabob.

**Comment by ableman** [comment] 2015-04-15 16:25
I can reproduce this pretty reliably on dev if using Incognito mode, on the Widgetize yourself page in Settings. Putting in the </div> tag doesn't seem to fix it. Also, I'm using sublime text, and the autocomplete doesn't seem to think there is a <div> tag to close at that point

**Comment by ableman** [comment] 2015-04-15 16:45
Reverting #1586 does fix it

![image](https://cloud.githubusercontent.com/assets/4017467/7164295/28367310-e354-11e4-8822-5b21751c4e2c.png)

**Comment by ableman** [comment] 2015-04-15 18:34
After some investigation, I think the widgetize yourself page is a little special. For example, here's the openhatch live site

![image](https://cloud.githubusercontent.com/assets/4017467/7166476/d519247a-e362-11e4-90d0-94bb694582fd.png)

Here's the live site in icognito mode
![image](https://cloud.githubusercontent.com/assets/4017467/7166506/024ef28a-e363-11e4-8f1c-d9cc0b1af141.png)

removing line [242](https://github.com/openhatch/oh-mainline/commit/ccafe6ace96eead2bf79f7d219fb6676b107909d#diff-25003d6f49c830c872ef6be3c4a7332aR242)

fixes this issue, but brings back the not sticking problem the #1586

**Comment by phildini** [comment] 2015-04-15 21:21
It looks like someone reverted and this fixed the issue? It's looking fine for me.

**Comment by ableman** [comment] 2015-04-15 22:16
Problem still there for me.

![image](https://cloud.githubusercontent.com/assets/4017467/7170355/53691442-e382-11e4-95db-90ac38d43c3f.png)

**Comment by ehashman** [comment] 2015-04-16 20:49
Appears to be fine with the main page (which was the most notable breakage for me) so I'm fine with resolving this.

However, the footer is still far off to the left (as reported above by me iirc) on the individual missions pages (see http://openhatch.org/missions/git for instance).

**Comment by Sanal05** [comment] 2015-05-06 18:32
Whenever I open openhatch I notice the page to get overlapped with another information specified in the bottom of the page. So I the last few lines of the information of the page gets hidden. 
I tried to inspect the page and came to see a <div id = "footer-wrapper"> </div> and so I simply delete the footer-wrapper in the id and then the overlapping problem gets resolved. But temporarily.
I think the footer-wrapper is not required in the main code of the page.

**Comment by ehashman** [comment] 2015-05-07 00:13
I don't know if #1627 broke this again, but the footer's now overlapping again :\

![screenshot-6](https://cloud.githubusercontent.com/assets/4706131/7506321/5d99684e-f42c-11e4-88ca-40a870ba3fb4.png)

**Comment by ableman** [comment] 2015-05-07 03:35
It probably did, if you look at #1608 all I did was remove the "bottom:0" line. #1627 put it back in. My best guess is that absolute does not mean what you would naturally assume it means http://www.w3schools.com/cssref/pr_class_position.asp

Note the description here "The element is positioned relative to its first positioned (not static) ancestor element"

So, it's not bottom: 0 relative to the bottom of the page. It's bottom:0 relative to some other element, which makes it overlap.

**Closed** 2015-06-17 12:29 UTC
Labels: css, pri:urgent, stat:reopened, usability
