### ISSUE TITLE
Fix website for https - redirect to "www." or allow https access without it.

### ISSUE THREAD

**Issue by david-a-wheeler** [openhatch/oh-mainline#1683] opened 2015-07-22 18:47 UTC
Can you fix the openhatch.org website when accessing via https?  It doesn't like URLs that omit "www".

This URL fails to open:
https://openhatch.org/wiki/Easy_bugs_for_newcomers

This URL succeeds:
https://www.openhatch.org/wiki/Easy_bugs_for_newcomers

Please redirect all references to https://openhatch.org to the “www.” Version, or allow both.

The error messages on failures vary by browser. Here's the Firefox error message:
The connection was interrupted
The connection to openhatch.org was interrupted while the page was loading.
*    The site could be temporarily unavailable or too busy. Try again in a few moments.
*    If you are unable to load any pages, check your computer's network connection.
*    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

Here's the Chrome error message:
This webpage is not available
ERR_CONNECTION_CLOSED
Reload Hide details
The webpage at https://openhatch.org/wiki/Easy_bugs_for_newcomers might be temporarily down or it may have moved permanently to a new web address.

Thanks!

**Comment by paulproteus** [comment] 2015-07-22 21:17
Hi @david-a-wheeler ! I've long respected your work, so it's an honor to see you here.

I can't reproduce the problem you are reporting, so I wonder if it was a transient error perhaps related to our use of CloudFlare.

Let me know if you can still reproduce it, or have hints on how I can reproduce it here. Thanks!

**Comment by david-a-wheeler** [comment] 2015-07-22 22:21
On Wed, 22 Jul 2015 14:17:12 -0700, Asheesh Laroia <notifications@github.com> wrote:
> Hi @david-a-wheeler ! I've long respected your work, so it's an honor to see you here.

Thanks!!!!

> I can't reproduce the problem you are reporting, so I wonder if it was a transient error perhaps related to our use of CloudFlare.
> Let me know if you can still reproduce it, or have hints on how I can reproduce it here. Thanks!

It's not transient; it still happens in my environment.  That said, my environment does a lot of filtering checks and if stuff "looks funny" the packets are just thrown away (!).  Problem is, I get no info on WHY there's a problem :-(.

One common reason is that the certificate's  CN is misleading.  E.G., CN=www.openhatch.org ... in which case that won't validate when you try to access it as "openhatch.org".  Unfortunately, I'm currently at a captive site and I can't fully test that.  That said, I asked "https://www.ssllabs.com/ssltest/" to check openhatch.org and it didn't scream.  What's more, it *looks* okay; openhatch.org is specifically listed as a valid alternative name.

I'll see if I can get more info on my end.  If you can think of something for me to check, let me know!

**Comment by paulproteus** [comment] 2015-07-22 22:25
I wonder if your IP address block reaches different CloudFlare servers than
I see, and that the CloudFlare servers you're seeing are broken. Totally
possible since they're a CDN. Hmm.​

I also wonder if CloudFlare is disconnecting the connection because it
thinks you're some kind of harmful bot? Hmm. I've changed the security
settings from "Low" to "Essentially Off".

**Comment by lwm** [comment] 2015-07-23 11:27
Just pinging in here to say that hitting the following URL succeeded for me.

    https://openhatch.org/wiki/Easy_bugs_for_newcomers

Tested on an up to date Firefox 39.0.

**Comment by ehashman** [comment] 2015-07-30 15:56
Both URLs are working for me, testing also on Firefox 39.0 (of the Ubuntu flavour).

**Comment by willingc** [comment] 2015-08-10 18:25
I've tested https://openhatch.org as well as https://openhatch.org/wiki/Easy_bugs_for_newcomers on Chrome as well as running another "https://www.ssllabs.com/ssltest/" (which as expected based on @david-a-wheeler's earlier results).

I'm going to close this issue. @david-a-wheeler, if your browser is still complaining about 'www', please feel free to reopen this issue. Thanks for reporting this :penguin:

**Closed by willingc** 2015-08-10 18:25 UTC
Labels: pri:bug, stat:chatting
