### ISSUE TITLE
Login righthand navigation is misleading

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#451] opened 2014-08-08 02:46 UTC
<b>Comment by <a href='https://openhatch.org/people/rafpaf/'>rafpaf</a>:</b><dl><dd>This is a low-priority UI bug, imho. Go to <a href="http://openhatch.org/account/login/">http://openhatch.org/account/login/</a> 
and click "login with a password". Now click "login with OpenID".

When you click on these links, the bolded link at the top of the "Relatedly" 
section changes. This aspect of the UI accidentally matches a traditional design 
pattern: "vertical list of links, one link bolded". In this pattern the bold 
link indicates the currently selected page. (We use this pattern in the account 
settings pages.) The login pages seem to be mimicking this pattern and in so 
doing mislead me.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Thanks (-:
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Now I understand.

A reasonable resolution of this bug is to put *all* account-related pages into
that right-hand-side box.

I'll do that right now, why the heck not.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Erm, yargh, now there are too many links in the sidebar.

I'm going to stop working on this for now and be confused.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>I'm not currently working on this. Someone else can grab it!
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/palhmbs/'>palhmbs</a>:</b><dl><dd>I'd like to try this - if you think it's not too hard / much bother.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>It would be totally great if you would think this through.

I have made no progress on this bug because I havne't thought about what a 
good solution would be. If you think of one and submit a patch, that would 
rock my world.

(It probably isn't that hard / doesn't require that much thinking. I'm 
just a scatter-brain.)
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/palhmbs/'>palhmbs</a>:</b><dl><dd>I've been thinking, for a start I think "Relatedly" is a terrible word to use.
How bout "Login with", "Login types" or "Login Methods"  ??

Center the login to the middle of the screen, instead of just using 1/3 of the 
screenspace eg: "Login with a password".
Put all the "Login Methods" in a top menu / dropdown.

Also, we should move "What is OpenID? &amp; "Forgot your password?" out of 
"Relatedly". 

Let's make this login screen spunky....
Create a extraneous links free login page (getting rid of site navigation header 
and footer stuff), with no hatch background - Just have the openhatch logo then 
when logging in maybe a processing cartoon / gif (aldeka) ?

Looking forward to comments.
Paul
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/palhmbs/'>palhmbs</a>:</b><dl><dd>bump - does nobody want to discuss this further?
If not should we get a mockup/s done?
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/jessica/'>jessica</a>:</b><dl><dd>Started a diagram:
<a href="https://cacoo.com/diagrams/YVZ6b3aXKkbQdQz1">https://cacoo.com/diagrams/YVZ6b3aXKkbQdQz1</a>

Anyone can edit, probably. Maybe. My first time using cacoo other than as an 
observer :)

Spunk could also just be when you click "log in" in the upper right that it drops 
down a username/password field or openid link / click here to login with Google.

Or even replacing login top right with [username] [password] [Login] and when 
logged in it's the usual profile name (username) and Logout .

Since cartoons are on most of the other pages, we should probably continue that 
brand. A cheater way would be to use the top of /people/ ? And creating an account 
is adding you to the "people" and logging in is done by "people" so might fit :)
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/palhmbs/'>palhmbs</a>:</b><dl><dd>Can we agree on getting rid of all site navigation?
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/jessica/'>jessica</a>:</b><dl><dd>Like this? <a href="http://www.vimeo.com/log_in">http://www.vimeo.com/log_in</a>

Or <a href="https://www.facebook.com/">https://www.facebook.com/</a> (when not logged in)?
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/palhmbs/'>palhmbs</a>:</b><dl><dd>More like this - (see attached screenshot).
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/pythonian4000/'>pythonian4000</a>:</b><dl><dd>I like this - it is self-contained and not specific to any part of OpenHatch, so
the central login system makes a bit more sense.

Also, it should have a "Cancel" or "Back" button/link that returns you from
whence you came.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/palhmbs/'>palhmbs</a>:</b><dl><dd>I've had a chat with paulproteus on IRC, and it's awesome to 
get feedback on issues with him there! bd

So, what we have decided is:

1. We'd love a login drop-down from the main openhatch login 
link...
<a href="http://uxmovement.com/forms/dropdown-login-boxes-for-faster-">http://uxmovement.com/forms/dropdown-login-boxes-for-faster-</a>
login

2. That we should have a off-site login page that will contain 
exactly the same content like...
<a href="http://gawker.zendesk.com/access/unauthenticated?return_to=http">http://gawker.zendesk.com/access/unauthenticated?return_to=http</a>
%3A%2F%2Fgawker.zendesk.com%2Flogin

3. Dropdowns are ugly and less comfortable than buttons &amp; tabs.

4. Sign-up and login pages are exactly the same, so merge 
them. - 
        a. If you have an account already then you have the 
option to add / merge that new login type with a your current 
openhatch account.
        b. If you don't have an account already then using 
whatever login type will create a new openhatch account.
        c. Things to validate duplicate users should be 
location or username, and you can't login using another login 
type that has been already been used with an existing account. 
(need more suggestions...)

so I will get a couple of mockups together...
A) for on-site drop-down login 
B) For off-site (Roundup &amp; wiki)

And I think we can still do a cool throbber to show whilst 
sign up / login happens - something spunky, that shows that 
how OpenHatch is so awesome.
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/palhmbs/'>palhmbs</a>:</b><dl><dd>Sorry, defintely not bitesize anymore!
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>Goodness. I do not remember what this bug is about. Adding Flora -- can you give 
this a read-through and write what you think?
   
</dl></dd><hr/>

<b>File at http://roundup-archive.openhatch.org/bugs/file252/login_mockup.png by palhmbs</b>

Status: <b>chatting</b>
Nosy List: <b>  aldeka, florapdx, jessica, palhmbs, paulproteus, rafpaf </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>136</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue136'>view archived page</a>)
Last modified: <b>2013-08-03.02:10:51</b>

**Comment by onceuponatimeforever** [comment] 2015-04-09 05:06
I'll work on this during the pycon 2015 week to streamline the signup/login nav bar.

**Comment by ehashman** [comment] 2015-04-16 20:46
I'm not comfortable with closing this bug as I don't think it addresses a number of comments in the original issue, namely:

1. Adding a drop down login on the main page per @paulhomebus' feedback
2. Changing the "Relatedly" header over alternate login methods

This issue does appear to have spiralled in scope a bit, but I'd like to see these ideas addressed (possibly by moving them into other issues?) before we close this.

**Comment by NPrescott** [comment] 2015-05-21 06:49
I've opened a new issue, #1654, so that this issue might be closed/cleared. Just doing a bit of backlog grooming and trying to identify those things which have been addressed vs. need addressing.

I opted not to include the issue of "relatedly" in the new issue because it seems as though the point would be moot were the suggested sign-in implemented.

**Comment by ehashman** [comment] 2015-06-20 22:14
Thanks @NPrescott for splitting off the dropdown login issue.

I'm going to leave this issue open as I agree that the "Relatedly" header is confusing, and I think that text needs to be changed. This means this is a bitesize feature request!

**Steps to reproduce:**

1. Hit the "log in / sign up" button in the navigation bar on openhatch.org.
2. Notice that there is a right-hand navigation section in a grey box that begins with "Relatedly".

**Desired behaviour:**

The grey box is more meaningfully organized. Perhaps this could just be a text change ("Relatedly" -> ???) or perhaps the box could be divided into more logical parts (signup/login without a password, sign in with a password ... what is OpenID?) This is up to the committer.

**Where do I start?**

You can find the template for the login page here (I'm focusing on the "Relatedly" section): https://github.com/openhatch/oh-mainline/blob/master/mysite/account/templates/account/login.html#L110

**Comment by jamessimas** [comment] 2015-07-04 07:02
@ehashman,

I'll start working on this tomorrow and should have something in a day or two.

**Comment by ehashman** [comment] 2015-07-12 20:51
#1677 closes this; see #1654 for the other mentioned requests.

**Closed by ehashman** 2015-07-12 20:51 UTC
Labels: bitesize, pri:bug, stat:chatting, usability
