### ISSUE TITLE
500 Server Error inside "Diffing your Changes" training mission

### ISSUE THREAD

**Issue by Devon0831** [openhatch/oh-mainline#1673] opened 2015-06-27 17:49 UTC
When submitting my output to be checked, the website redirects me to a page titled "Error 500 (server  error)". I tried refreshing the page, submitting different text, and redoing the instructions, but the webpage always says "The file resulting from patching does not have the correct contents" (if only part of the output is pasted into the box) or "Error 500 (server error)" (if the entire output message is pasted into the box). 

The message I am pasting into the box is this:

```
Index: README
===================================================================
--- README	(revision 3)
+++ README	(working copy)
@@ -1,5 +1,5 @@
 The secret word needed to infiltrate the compound is in word.txt. You
-also will need to be wearing a red hat.  Good luck on your mision!
+also will need to be wearing a red hat.  Good luck on your mission!
 
   -- Mr. Bad
```

**Comment by ehashman** [comment] 2015-07-12 20:40
This is a duplicate of #1547, which was marked as a dupe of #1399. Closing.

**Closed by ehashman** 2015-07-12 20:40 UTC
