### ISSUE TITLE
Submit button overlaps text field in first Git mission

### ISSUE THREAD

**Issue by chums923** [openhatch/oh-mainline#1556] opened 2015-03-12 17:05 UTC
The submit button in the first mission over is covering part of the text field it related to. Most likely an easy CSS fix. Not sure if it's an issue with the other missions as well. Will update if I find similar errors. 

![ohbug](https://cloud.githubusercontent.com/assets/2695564/6623220/fdfe8d3c-c8b7-11e4-8433-931c296462f4.png)

I am using firefox 36.0.1 on Ubuntu 14.04. This wasn't an issue when I looked at the page with Chrome. Sounds like a byte-sized task?

**Comment by onceuponatimeforever** [comment] 2015-04-09 04:40
I can't replicate this on either a firefox, safari, or chrome browser. :confused:

**Comment by chums923** [comment] 2015-04-09 16:42
Hm, bummer. You sure you're on the right mission? Maybe it's the OS then? Either way, looks like someone submitted a PR fixing this issue a few days ago

**Comment by shaunagm** [comment] 2015-04-09 17:47
I can reproduce, also Ubuntu 14.04, Firefox 36.0.4.  It's fine on Chrome for me.
![overlap](https://cloud.githubusercontent.com/assets/1179362/7073050/ba6f61a0-debe-11e4-81db-22dc61a42a96.png)

**Comment by NPrescott** [comment] 2015-04-17 06:14
Can't reproduce on Firefox 37.0.1 under OSX 10.9.5 (or Chrome for that matter). I don't suppose we yet have OS specific tagging?

![screen shot 2015-04-17 at 12 57 33 am](https://cloud.githubusercontent.com/assets/4661088/7196786/08245f10-e49e-11e4-93f7-9d4b8d2a77f8.png)

For the sake of reference, this looks like it's being tackled in #1572

**Comment by dkalaluhi** [comment] 2015-04-29 18:19
Alignment looks correct for me as well.

*OS*:
_Windows 7 Enterprise SP 1_

*Browser:* 
_Chrome Version 42.0.2311.90 m_
_IE 9.0.8112.16421_

**Comment by rcrimp** [comment] 2015-05-14 01:27
Unable to reproduce the button overlap on GNOME, Fedora 21 with either firefox or chrome.
The the button is noticeably lower with firefox, such that it does not align vertically with the textfield

Firefox version: 37.0.2
Google Chrome version: 42.0.2311.135

**Comment by ehashman** [comment] 2015-06-21 18:44
![misaligned](https://cloud.githubusercontent.com/assets/4706131/8272905/293c3792-1813-11e5-92b9-4be163334600.png)

This what's currently in production, as viewed on Firefox 38.0 for Linux Mint Rebecca (17.1).

**Comment by igorsteinmacher** [comment] 2015-10-01 18:19
Checked on Iceweasel (Firefox) Debian 8.1, the behaviour is the same as the one reported in this issue.
To make the UI in consonance with that on https://openhatch.org/missions/git/checkout (see screenshot below, we need to change the style of the input element, easily fixing the issue. 

![checkoutgit](https://cloud.githubusercontent.com/assets/2953768/10229628/8818ff02-684f-11e5-8e1a-5e3986156cdf.png)
I will place a PR to fix it. Tested on Chrome and Iceweasel in Windows and Debian

**Comment by felipevolpone** [comment] 2015-10-26 21:06
With this commit https://github.com/igorsteinmacher/oh-mainline/commit/3248c22d091727704b23177cad71c8af1d3b94f6 I think this issue can be closed so. What do you think?

**Comment by ehashman** [comment] 2015-10-27 16:48
This is outstanding in #1715 which has not yet been merged, so not quite yet :) I think that's on the review backlog.

**Closed** 2015-10-27 16:50 UTC
Labels: bitesize, css, frontend, missions, pri:bug, stat:resolved
