### ISSUE TITLE
when watching projects list, clicking on expand doesn't alter the name expand to collapse

### ISSUE THREAD

**Issue by imported-from-roundup** [openhatch/oh-mainline#1035] opened 2014-08-08 02:54 UTC
<b>Comment by <a href='https://openhatch.org/people/jesstess/'>jesstess</a>:</b><dl><dd>20:12 &lt; dardevelin&gt; it's just a simple bug, when watching projects list,
clicking on expand doesn't alter the name expand to collapse 
20:15 &lt; dardevelin&gt; probably can be fixed by identifying the node count and the
after using var expnd = document.getElementsByClassName('expand'); var expnd_l =
expnd[0].getElementsByTagName('a'); 
                    expnd_l.innerHtml = "collapse" or something like that 
20:15 &lt; dardevelin&gt; not sure I'm not a js guru 
20:16 &lt; dardevelin&gt; expnd[ 0 ] (0 is the node in question, so something needs to
keep track of witch node is );
20:16 &lt; dardevelin&gt; it could just well be set while generating the page
   
</dl></dd><hr/>

<b>Comment by <a href='https://openhatch.org/people/paulproteus/'>paulproteus</a>:</b><dl><dd>I just tested it, and this seems resolved. Marking as such.
   
</dl></dd><hr/>

Status: <b>resolved</b>
Nosy List: <b>  jesstess, paulproteus </b>
Priority: <b>bug</b>
Imported from roundup ID: <b>720</b> (<a href='http://roundup-archive.openhatch.org/bugs/issue720'>view archived page</a>)
Last modified: <b>2014-02-08.04:54:32</b>

**Comment by ehashman** [comment] 2015-04-17 02:48
Closing as a duplicate of the more recent #1536.

**Closed by ehashman** 2015-04-17 02:48 UTC
Labels: pri:bug, stat:reopened
