### ISSUE TITLE
No Advanced search by project category and/or technology/library

### ISSUE THREAD

**Issue by rZeton** [openhatch/oh-mainline#1675] opened 2015-06-30 22:24 UTC
Advanced search by project category and/or technology/library would be nice.

I am for example not very interested in webdev stuff, which seems to be most of items. Some advanced search or filtering options would be nice to have.

Showing only 10 by page is not enough. Should be able to customise it.

**Comment by ehashman** [comment] 2015-07-12 20:47
There are a few bugs filed currently re: advanced searching, such as #1438 and #1242.

Showing only 10 bugs by page is a duplicate of #1198.

Hence, I'm going to close this as a duplicate.

**Closed by ehashman** 2015-07-12 20:47 UTC
