### ISSUE TITLE
The 'Add Your Project' page is wonky (CSS?)

### ISSUE THREAD

**Issue by SarahRK** [openhatch/oh-mainline#1554] opened 2015-03-08 19:39 UTC
The 'Want to Chat' Link is almost entirely hidden (I can see the 'W' but nothing else). 

The whole lefthand column looks wonky (why are the 1st two in their own box?).
![screen shot 2015-03-08 at 2 24 22 pm](https://cloud.githubusercontent.com/assets/4283226/6547226/1b2dd9aa-c5a0-11e4-9a6d-257d391e3d4b.png)

**Comment by ehashman** [comment] 2015-04-11 20:01
This is a duplicate of #1337. Closing and I'll move these tags there.

**Closed by ehashman** 2015-04-11 20:01 UTC
Labels: css, frontend, pri:bug, stat:unread
