### ISSUE TITLE
Github Project issues not seen by openhatch

### ISSUE THREAD

**Issue by impaktor** [openhatch/oh-mainline#1515] opened 2015-01-03 19:19 UTC
I added a project three weeks ago:
https://openhatch.org/projects/pioneer
and added a tracker:
https://openhatch.org/customs/edit/github/379/pioneer
to scrape our github:
 https://github.com/pioneerspacesim/pioneer

But no issues are being picked up. 

I've compared our setup with other github projects on openhatch like [ipython](https://openhatch.org/customs/edit/github/118/ipython), and their setup looks the same to me, and their bugs are being tracked by openhatch.

Any hints at what could be wrong would be greatly appreciated.

**Comment by pdurbin** [comment] 2015-01-03 19:25
See also:

- http://irclogs.jackgrigg.com/irc.freenode.net/openhatch/2014-12-29#i_3536111
- http://irclogs.jackgrigg.com/irc.freenode.net/openhatch/2014-12-31#i_3537561
- http://irclogs.jackgrigg.com/irc.freenode.net/openhatch/2015-01-03#i_3539057

**Comment by willingc** [comment] 2015-01-03 20:01
@ehashman @paulproteus I spent some time going through this issue today. What is odd is that the bug tracker does not display here http://openhatch.org/+projedit/pioneer
Yet it is accessible via https://openhatch.org/customs/edit/github/379/pioneer

**Comment by ehashman** [comment] 2015-01-04 05:08
Here's the log entry showing the scrape failed:

```
2015-01-04 04:56:48+0000 [Spider for importing using oh-bugimporters] DEBUG: Crawled (403) <GET https://api.github.com/repos/pioneerspacesim/pioneer/issues?state=open> (referer: None)
2015-01-04 04:56:48+0000 [Spider for importing using oh-bugimporters] DEBUG: Ignoring response <403 https://api.github.com/repos/pioneerspacesim/pioneer/issues?state=open>: HTTP status code is not handled or not allowed
```

What could be causing a 403?

**Comment by paulproteus** [comment] 2015-01-04 18:44
Huge thanks to all y'all for doing this investigative work. I had misunderstood the problem.

With @ehashman 's help I filed https://github.com/openhatch/oh-bugimporters/issues/110 which addresses the technical side of getting this fixed, I think.

**Comment by ehashman** [comment] 2015-01-04 19:00
From IRC:

```
13:25 < ehashman> aha: https://developer.github.com/v3/#rate-limiting
13:26 < ehashman> are we making >5000 requests per hour?
13:28 < paulproteus> Interesting question. Possibly, if their API reacts 
                     quickly.
13:28 < paulproteus> I think as soon as they respond to one request, we send 
                     the next.
13:29 < paulproteus> Max 1 simultaneous connection per host
```

We'll see if rate-limiting the requests via Scrapy fixes the problem. Closing this issue as we've refiled it under the applicable repo. Thanks for your report, @impaktor!

**Comment by willingc** [comment] 2015-01-04 19:55
@ehashman @paulproteus Thanks for the fix :)

I learned recently that GitHub has different rate limits for authenticated vs. unauthenticated requests. https://developer.github.com/v3/#rate-limiting might help if we hit a limit.

@impaktor Thanks for your patience and @pdurbin for keeping the issue moving forward :)

**Comment by laarmen** [comment] 2015-01-05 19:05
I *think* this was supposed to be fixed during the last run, however the Pioneer bug tracker still returns a 403 in the logs at http://inside.openhatch.org/crawl-logs/scrapy.2015-01-05.en3a.log

Was it deployed in production at that time?

**Comment by impaktor** [comment] 2015-01-06 09:15
pioneer is not in latest logs ([2015-01-15](http://inside.openhatch.org/crawl-logs/scrapy.2015-01-06.MMYM.log)), but I still can't see any of our issues on Openhatch. Nor are there any "volunteer opportunities" indexed, which I assume is the same problem.

Looking at other github projects like https://openhatch.org/projects/Thrive their [issues](https://github.com/Revolutionary-Games/Thrive/issues) marked "easy" on github are not indexed either, nor are they in the latest logs.

So this is (still) not isolated to pioneer, and not due to our bitesize flag having a hyphen ("Bite-size"), since Thrive uses "easy", which was stipulated on IRC.

Returning to another github project: ipython, this 24 h old issue: https://github.com/ipython/ipython/issues/7378 is indexed by openhatch.

**Comment by willingc** [comment] 2015-01-06 14:50
@impaktor and @laarmen, I'm sorry that the latest changes didn't get the root cause(s) resolved. I thank you for your assistance.

@paulproteus, @ehashman, @pdurbin: I'm reopening this issue until it and https://github.com/openhatch/oh-bugimporters/issues/110 are working as expected.

I'm starting an etherpad about the flow from bug tracker profile submission to actual display of bugtracker info so that I can write a doc for developers on this process. I will post the link in a future message.

**Project Information Bug Trackers Tab**
I would like to see the https://openhatch.org/+projedit/pioneer and the "Bug Trackers" tab display the tracker before we close this issue.
![screen shot 2015-01-06 at 06 21 27](https://cloud.githubusercontent.com/assets/2680980/5629823/76543c2a-956c-11e4-8fc4-a870601c0fb9.png)

Currently, https://openhatch.org/+projedit/IPython returns a 500 error :(
![screen shot 2015-01-06 at 06 25 23](https://cloud.githubusercontent.com/assets/2680980/5629915/a440f3fc-956d-11e4-90e4-e5fbe73ece90.png)

Here is an example of a project (Amarok) that has a Bugzilla tracker and its correct display: 
![screen shot 2015-01-06 at 06 33 15](https://cloud.githubusercontent.com/assets/2680980/5630014/beefb8f4-956e-11e4-9b12-1772a5a541d6.png)

**Comment by dirkbaechle** [comment] 2015-01-14 22:57
Might be related to https://github.com/openhatch/oh-bugimporters/issues/108

**Comment by thomasballinger** [comment] 2015-02-18 03:05
I'm seeing this too with bpython. From the logs it looks like this is happening a log:
~~~
tom-mba:~ tomb$ grep 'Crawled .200. .*api.github.com' scrapy.2015-02-17.30WG.log | wc
     105    1470   19505
tom-mba:~ tomb$ grep 'Crawled .403. .*api.github.com' scrapy.2015-02-17.30WG.log | wc
     129    1806   24190
~~~

**Comment by thomasballinger** [comment] 2015-02-18 03:46
Based on the logs from yesterday, I submit that we are not making more than 5000 requests, we're simply making 60 of them completely unauthenticated. See https://gist.github.com/thomasballinger/4d063186febfe4190283, the two times that requests succeed exactly 60 of them are made, and then the rest are 403s.

**Comment by willingc** [comment] 2015-02-18 03:49
@thomasballinger Thanks for the details. Is it possible/probable that GitHub has rate limited unauthenticated requests from us?

**Comment by thomasballinger** [comment] 2015-02-18 03:56
I think so. I bet if we authenticated (either basic auth with a github account, or adding some query params for oauth) this would fix it.

**Comment by willingc** [comment] 2015-02-18 04:24
After chatting on IRC with @thomasballinger and @ehashman, it may be possible to authenticate using scrapy middleware:
![screen shot 2015-02-17 at 20 23 49](https://cloud.githubusercontent.com/assets/2680980/6242412/0970bda2-b6e3-11e4-9389-b6277cd7e1cd.png)

**Comment by thomasballinger** [comment] 2015-02-18 06:04
I've described possible solutions at https://github.com/openhatch/oh-bugimporters/issues/110 but am having trouble running the code locally so can't suggest a fix.

**Comment by paulproteus** [comment] 2015-02-18 07:26
This is amazing research. Thanks all. I had no idea about the authorization
stuff. I will try to dig into this tomorrow or within the next few days.

**Comment by impaktor** [comment] 2015-02-27 15:26
> I will try to dig into this tomorrow or within the next few days.

Awesome. I'm Looking forward to getting the bugs from my/our project (pioneer) into openhatch.

**Comment by thomasballinger** [comment] 2015-03-08 15:35
What would be most helpful for me to do to help get this resolved? Unfortunately it's significantly affecting the quality of the OpenHatch bug suggestions because half of all GitHub bug scrapings are failing, so many issues which appear open have been closed for a month.

The two tasks seem to be
* modifying the code to read environmental variables for GitHub auth and adding these to requests
* creating a [GitHub OAuth application](https://github.com/settings/applications/new) and adding that information to the deployment environment (or creating GitHub account whose username and password can be used by the script)

The second probably needs to be done by OpenHatch folks.

**Comment by willingc** [comment] 2015-03-09 12:14
@thomasballinger Thank you for offering to help and for your continued, thoughtful patience. I agree that I would love to see the GitHub bug issues updated and working for our users. 

@paulproteus Do you want to pair on Thursday evening to see if we can try to make progress on this while I am in SF? 
cc/ @onceuponatimeforever @ehashman

**Comment by ehashman** [comment] 2015-04-11 20:15
Update: @paulproteus and I have talked about looking at this at the sprints. It is back on my radar now :)

**Comment by paulproteus** [comment] 2015-04-13 15:53
We're looking into this at sprints, too. Thanks!

**Comment by thomasballinger** [comment] 2015-04-26 15:06
Did anything happen with this offline during sprints? Sorry for noise, I might have some time today to try to get the scraper running locally again to suggest a fix.

**Comment by paulproteus** [comment] 2015-04-26 16:47
Hi @thomasballinger ! Yes -- we tested your fix, and we concluded it should work fine. Thank you for the research you did, the explanation of how to use the GitHub auth stuff, and for this ping.

I actually also have some time today to look into this, too. Given that, I propose that I ping you back here in about two hours with a status update, and we'll see how I've fared.

**Comment by paulproteus** [comment] 2015-04-26 16:48
I wish I had chased down the nice person who was working on this during sprints to find out exactly what code change he made. For now I'll quickly try to recreate it.

**Comment by paulproteus** [comment] 2015-04-26 18:38
FWIW, I am running a fresh crawl right now, and we'll see if my changes to oh-bugimporters fix this. If so, I'll submit a pull request.

**Comment by dirkbaechle** [comment] 2015-05-05 21:56
This looks like it has been fixed now. At least we finally see a list of open issues for the SCons project ( http://openhatch.org/projects/SCons ). So freaking awesome!
Big thanks to anyone involved in resolving this!!!

Remark: This probably resolves https://github.com/openhatch/oh-bugimporters/issues/108 as well...

**Comment by ehashman** [comment] 2015-05-05 22:47
@dirkbaechle: amazing!!! I am so happy this is finally fixed ^_^ I will mark the issues resolved.

**Closed by ehashman** 2015-05-05 22:47 UTC
Labels: bugimporters, pri:urgent, stat:in-progress

**Comment by willingc** [comment] 2015-05-06 03:16
@dirkbaechle Thank you for having huge patience. I'm so glad it is resolved and that SCons project tracker is now working :bouquet: :tea: :gift_heart: for being super to work with.

**Comment by impaktor** [comment] 2015-05-06 07:54
Thanks!

I now see 30 of our 295 open issues from our github tracker on openhatch. Not sure why though. We have `Bite-sized` flagged 3 issues, so I expected either all 295 or just 3 to show up in openhatch.

**Comment by ehashman** [comment] 2015-05-07 00:11
@impaktor: I can see that. Perhaps file a separate issue, possibly against openhatch/oh-bugimporters.
